# Generated by Django 4.0.4 on 2022-05-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_alter_privilege_privilege_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='privilege_owner',
            field=models.CharField(default='QMRITMQEQKRN', editable=False, max_length=12, unique=True),
        ),
    ]
