# Generated by Django 4.0.4 on 2022-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_alter_privilege_privilege_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='check_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='privilege_owner',
            field=models.CharField(default='MNILZEA5IZHB', editable=False, max_length=12, unique=True),
        ),
    ]
