# Generated by Django 4.0.4 on 2022-05-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_alter_privilege_check_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='privilege_owner',
            field=models.CharField(default='JXAR2XPPIW1M', editable=False, max_length=12),
        ),
    ]
