# Generated by Django 4.0.4 on 2022-05-19 18:08

import check.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_alter_privilege_privilege_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='check_count',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='privilege_owner',
            field=models.CharField(default=check.models.Privilege.generate_string, editable=False, max_length=12),
        ),
    ]
